In [1]:
Input_76181 = [77740
77756
77753
77326
76655
76664
77815
77087
77780
76656
77767
77782
77765
76660
77775
76784
77765
77766
77770
77772
];

Input_76210 = [77441
77449
77445
77452
77446
77457
77126
77459
77461
77462
77464
77466
77465
77467
77456
77163
77368
76620
76885
77447
77646
77349
77445
77471
77162
77353];

Input_76182 = [77326
77327
77368
77339
77352
77371
77370
77372
77373
77384
76681
77386
77393
76887
77394
77364
77395
77399
77387
77385
77389
77390
77391
77365
76623
77375
77682
77151
77374
77378
77392
77365
77395
77331
77163
77328
77352
77339
77338];


Input_76183 = [77434
77162
77446
77805
77460
77132
76623
77386
77151
77341
76691
77375
77371
77854
77328
77858
77592
76667
77862
77358
77389
77326
77395
77371
76629
77365
76181
76679
77868
77163
77872
76673
76661
77378];

Input_76201 = [76902
76903
76907
76912
76924
77021
77026
76918
77022
77034
77885
77039
76953
76909
76953
76924
76927
76930
76929
76931
76936
76940
76943
76942
76932
76933
76948
76950
76955
76962
76964];

Input_76200 = [77792
76622
77801
77802
77803
77805
77434
76697
77759
77806
76629
77390
77807
77809
76691
77365
76630
76691
77821
77122
76618
76656
76682
76660
76631];

Input_76185 = [
77352
77846
77386
77460
76664
77374
77815
77767
77806
77334
77339
77801
76655
77807
77794
76700
77588
77807
77930
77342];

Input_76186 = [77339
76660
77868
76656
77872
77357
77815
77328
77354
77352
77807
77390
76623
77369];

Input_76199 = [76618
76620
76622
76627
76701
76659
77767
76655
76664
76667
76656
77855
76659
76679
76660
76628
76181
76625
76673
76631
76698
76701
77816
76682
76684
77393
76688
76687
76690
76628
76692
76694
76629];

In [2]:
ConcatInputs = [Input_76181;Input_76182;Input_76183; Input_76210; Input_76201; Input_76200; Input_76185; Input_76186; Input_76199];
ConcatCells = [76181*ones(length(Input_76181),1);76182*ones(length(Input_76182),1);76183*ones(length(Input_76183),1);76210*ones(length(Input_76210),1);
        76201*ones(length(Input_76201),1);76200*ones(length(Input_76200),1);76185*ones(length(Input_76185),1); 76186*ones(length(Input_76186),1); 76199*ones(length(Input_76199),1)]
CommonInputHistogram = hist(ConcatInputs,length(ConcatInputs))[2]
length(ConcatCells)
length(ConcatInputs)
NumberOfBins = length(minimum(ConcatInputs):1:maximum(ConcatInputs))

 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in histrange(::Array{Int64,1}, ::Int64) at ./deprecated.jl:582
 in hist(::Array{Int64,1}, ::Int64) at ./deprecated.jl:645
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::String, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_string(::Module, ::String, ::String) at /Users/admin/.julia/v0.5/Compat/src/Compat.jl:464
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/admin/.julia/v0.5/IJulia/src/execute_request.jl:154
 in invokelatest(::Function, ::ZMQ.Socket, ::Vararg{Any,N}) at /Users/admin/.julia/v0.5/Compat/src/Compat.jl:475
 in eventloop(::ZMQ.Socket) at /Users/admin/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##18#24)() at ./task.jl:360
while loading In[2], in expression starting on line 4
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in #hist!#994(::Bool, ::Function, ::Array{Int64,1}, ::Array{Int64,1}, ::FloatRange{Float6

1750

In [3]:
using Plots
gr()
plot(ConcatInputs, ConcatCells,line=(:scatter), color = (:blues))
xlabel!("Input cell ID")
ylabel!("Output cell ID")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 76250 
 
 
 76500 
 
 
 76750 
 
 
 77000 
 
 
 77250 
 
 
 77500 
 
 
 77750 
 
 
 76185 
 
 
 76190 
 
 
 76195 
 
 
 76200 
 
 
 76205 
 
 
 76210 
 
 
 Input cell ID 
 
 
 Output cell ID 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [4]:
h = histogram(ConcatInputs, nbins = NumberOfBins)
xlabel!("Cell ID")
ylabel!("Count")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 76250 
 
 
 76500 
 
 
 76750 
 
 
 77000 
 
 
 77250 
 
 
 77500 
 
 
 77750 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 Cell ID 
 
 
 Count

In [5]:
using StatsBase
h = fit(Histogram,ConcatInputs, nbins = NumberOfBins)

To avoid this warning, specify closed=:right or closed=:left as appropriate.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in _check_closed_arg at /Users/admin/.julia/v0.5/StatsBase/src/hist.jl:11 [inlined]
 in #fit#89(::Symbol, ::Int64, ::Function, ::Type{StatsBase.Histogram{Int64,N,E}}, ::Tuple{Array{Int64,1}}) at /Users/admin/.julia/v0.5/StatsBase/src/hist.jl:298
 in (::StatsBase.#kw##fit)(::Array{Any,1}, ::StatsBase.#fit, ::Type{StatsBase.Histogram{Int64,N,E}}, ::Tuple{Array{Int64,1}}) at ./<missing>:0 (repeats 2 times)
 in #fit#92(::Array{Any,1}, ::Function, ::Type{StatsBase.Histogram}, ::Array{Int64,1}, ::Vararg{Array{Int64,1},N}) at /Users/admin/.julia/v0.5/StatsBase/src/hist.jl:352
 in (::StatsBase.#kw##fit)(::Array{Any,1}, ::StatsBase.#fit, ::Type{StatsBase.Histogram}, ::Array{Int64,1}) at ./<missing>:0
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::String, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys

StatsBase.Histogram{Int64,1,Tuple{FloatRange{Float64}}}
edges:
  76181.0:1.0:77931.0
weights: [2,0,0,0,0,0,0,0,0,0  …  0,0,0,0,0,0,0,0,0,1]
closed: left
isdensity: false

In [6]:
bins = (76181:1:77931)
bins[find(x->x==3,h.weights)]

14-element Array{Int64,1}:
 76623
 76629
 76655
 76664
 76691
 77163
 77326
 77328
 77371
 77386
 77390
 77395
 77767
 77815

In [7]:
A= [0.84
0.96
0.80
0.87
0.94
0.91
0.91
0.95
0.90
0.94
1.00
0.92
0.91
0.92
0.59
0.90
0.94
0.82
0.87
0.75
0.97
0.92
0.90
0.95
0.88
0.81
0.89
0.89
0.77
0.89
0.89
0.90
0.98]
B = [0.95
0.95
0.73
0.97
0.99
0.88
0.95
0.94
1.00
0.96
0.84
0.96
0.97
0.93
0.98
0.90
1.00
0.97
0.95
1.00
0.96
0.98
1.00
0.93
1.00
0.83
0.99
0.94
1.00
0.96
1.00
0.93
0.96]

33-element Array{Float64,1}:
 0.95
 0.95
 0.73
 0.97
 0.99
 0.88
 0.95
 0.94
 1.0 
 0.96
 0.84
 0.96
 0.97
 ⋮   
 0.98
 1.0 
 0.93
 1.0 
 0.83
 0.99
 0.94
 1.0 
 0.96
 1.0 
 0.93
 0.96

In [16]:
#using StatPlots
#using PyPlot
gr()

x = []
y = []
for i in 1:length(A)
    push!(x, [1,2])
    push!(y, [[A[i], B[i]]])
end 
#x = repmat([[1 2]] , length(A))
#y = [A B]
lab = ["PlayerA", "PlayerB"]
plot(x,y, line=( :solid,2), marker = (:dot,15), leg=false, xaxis=("Player", font(40)), yaxis=("Accuracy", font(40)))
#boxplot!(A, leg = false)
#boxplot!(B)
xlims!(0,3)
xticks! = 1:2
xlabel!("Player#")
ylabel!("Accuracy F1 score")
savefig("PlayerAccuracies.svg")

In [199]:
y

33×2 Array{Float64,2}:
 0.84  0.95
 0.96  0.95
 0.8   0.73
 0.87  0.97
 0.94  0.99
 0.91  0.88
 0.91  0.95
 0.95  0.94
 0.9   1.0 
 0.94  0.96
 1.0   0.84
 0.92  0.96
 0.91  0.97
 ⋮         
 0.92  0.98
 0.9   1.0 
 0.95  0.93
 0.88  1.0 
 0.81  0.83
 0.89  0.99
 0.89  0.94
 0.77  1.0 
 0.89  0.96
 0.89  1.0 
 0.9   0.93
 0.98  0.96